# nixpacks.toml

[phases.setup]
nixPkgs = [
    "pkgs.python311", 
    "pkgs.glib", 
    "pkgs.libGL", 
    "pkgs.xorg.libSM", 
    "pkgs.xorg.libX11", 
    "pkgs.xorg.libXext", 
    "pkgs.xorg.libXrender"
]
